- name : hello world
  hosts : local
  connection: local # NO NEED OF USER NAME AND PASSWORD IN COMMAND LINE in mobxtream because WE USED LOCAL HOST HERE SO 
  tasks:
   - name: print message 
     ansible.builtin.debug:
      msg: "Be a man dude"






      
# PLAY [hello world] ********************************************************************************************************************************************************************

# TASK [Gathering Facts] ****************************************************************************************************************************************************************
# ok: [localhost]

# TASK [print message] ******************************************************************************************************************************************************************
# ok: [localhost] => {
#     "msg": "HELLO MY BOY U JUST NEED TO LEVEL UP DAY BY DAY"
# }

# PLAY RECAP ****************************************************************************************************************************************************************************
# localhost                  : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0


