- name : hello world
  hosts : local
  connection: local # NO NEED OF USER NAME AND PASSWORD IN COMMAND LINE in mobxtream because WE USED LOCAL HOST HERE SO 
  tasks :
   name: print message 
  ansible.builtin.debug:
   msg: " HELLO MY BOY U JUST NEED TO LEVEL UP DAY BY DAY "
