- name: PLAY1
  hosts: local
  connection: local
  tasks:                             #IT  IS PLAY 1 , TASK 1
    - name: hello from play 1 task 1
      ansible.builtin.debug:
       msg: "HELLO I AM TASK 1 FROM PLAY 1"

    - name: hello from play 1 and task 2 
      ansible.builtin.debug:             #IT  IS PLAY 1 , TASK 2
        msg: "HELLO I AM TASK 2 FROM PLAY 1"

      #----------------------------------------------------------------------------------------------------------

#🔥 Execution Flow (VERY IMPORTANT)

# Ansible runs top → bottom

# Step-by-step:
# ▶️ Run PLAY1
# Task1
# Task2
# ▶️ Then run PLAY2
# Task1
# Task2
#---------------------------------------------------------------------

# Play	Group of tasks for specific host

# Task	Single action (module execution)

#-------------------------------------------------------------------

# FORMAT:

#play
#   tasks
#     task
#       module
#         arguments