- name: Play level variables
  hosts: local
  connection: local
  vars:
   COURSE: DEVOPS WITH AWS
   DURATION: REALLY DONT KNOW HAVE TO COMPLETE IT QUICKLY
   STUDENT: K.JAYAVARDHAN
  tasks:
  - name : Print it
  ansible.builtin.debug:
    msg: "i am {{ STUDENT}} , I WANT TO COMPLETE {{ COURSE }} , BUT {{ DURATION }} THANK U "
