- name: Taskwise variables
  hosts: local
  connection: local
  vars:
   COURSE: PYTHON
   DURATION:  WITH IN 40 DAYS
  tasks:
  - name: About spoken english calss
    vars:
     COURSE: ENGLSH
     DURATION:  WITH IN 6 MONTHS
    ansible.builtin.debug:
      msg: " i am learning {{ COURSE }},  I think i will finish  it {{ DURATION }}"

  - name: About python
    ansible.builtin.debug:
      msg: " i am learning {{ COURSE }}, I think i will finish it {{ DURATION }}"


  