- name: variable files
  hosts: local
  connection: local
  vars_files:
  - info.yaml 
  tasks:
  - name: information of course
    ansible.builtin.debug:
      msg: "my name is {{ NAME }} I WILL COMPLPETE MY {{ COURSE }} WITH IN {{ DURATION }}"

      