- name: LOOPS
  hosts: local
  connection: local
  tasks:
  - name: PRINT GIVEN INFO
    ansible.builtin.debug:
      msg: "{{ item }}IS MY INSPIRATION" # HERE {ITEM} IS RESERVED/BUILTIN KEYWORD FOR LOOPS
    loops:
    - VIRATKOHLI
    - PURI
    - RONALDO
    - VXLIFTS