- name: INSTALLING AND DELETING THE PACKAGES BY USING LOOPS
  hosts: Frontend
  become: yes
  tasks:
  - name: installing and removing the packages
    ansible.builtin.package:
      name: "{{ item.name }}"
      state: "{{ item.state }}"

    loop:
    - { name: 'nginx', state: 'present'}  #INSTALLING
    - { name: 'mysql', state: 'absent'} #deletion
    - { name: 'nginx', state: 'absent'} #deletion
