#► 1 [DEFAULT]
- name: Functions
  hosts: local
  connection: local
  vars:
    persons: "virat,ronaldo,speed,andrewtate,randyorton"
  tasks:
  - name: checking undefined names/variables
    ansible.builtin.debug:
      msg: " HI AM {{ person | default ('vardhan') }} " # defauls is a function
# ------------------------------------OUTPUT--------------------------------
# ►IN ANSIBLE
#   FUNCTIONS == FILTERS 
# TASK [checking undefined names/variables] *****************************************************************************
# ok: [localhost] => {
#     "msg": " HI AM vardhan "
# }
#---------------------------------------------------------------------------------
# ►SEE FOR ABOVE THIS WE NEVER DEFINED ANY VARIABLE AS PERSON BUT WE GIVEN VARIABLE AS PERSON SO  WE HAVE GIVEN  DEFAULT VALUE TO THAT VARIABLE TO THAT AS VARDHAN.
# ►SO IT JUST FIRST CHECKS THE VARIABLE AND THEM PROCEED TO USE DEFAULT VARIABLE
# ---------------------------------------------------------------

#► 2 [SPLIT] convert string into lists
  - name: print names 
    ansible.builtin.debug:
      msg: " HI {{ persons | split (',') }} "

# -----------------------output--------------------
# TASK [print names] 
# ok: [localhost] => {
#     "msg": " HI ['virat', 'ronaldo', 'speed', 'andrewtate', 'randyorton'] "
# -------------------------------------------------

#► TO GET NAMES ONE BY ONE BY USING LOOP

  - name: print one by one
    ansible.builtin.debug:
      msg: " HI {{ item }} "
    loop: "{{ persons | split (',') }}"

# -------------------------------OUTPUT----------------------
    
# TASK [print one by one] 
# ok: [localhost] => (item=virat) => {
#     "msg": " HI virat "
# }
# ok: [localhost] => (item=ronaldo) => {
#     "msg": " HI ronaldo "
# }
# ok: [localhost] => (item=speed) => {
#     "msg": " HI speed "
# }
# ok: [localhost] => (item=andrewtate) => {
#     "msg": " HI andrewtate "
# }
# ok: [localhost] => (item=randyorton) => {
#     "msg": " HI randyorton "
# }

# ------------------------------------------------------------------
#► DICT TO LIST
  - name: convert map into list
    vars:
      course:
        name: ansible
        duration: 10HR
        student: vardhan
    ansible.builtin.debug:
      msg: "Course Info: {{ course | dict2items  }}"
#► LIST TO DICT 
  - name: convert list into map
    vars:
      course:
      - {'key': 'name', 'value': 'ansible'}
      - {'key': 'duration', 'value': '10HR'}
      - {'key': 'student', 'value': 'vardhan'}
    ansible.builtin.debug:
      msg: "Course Info: {{ course | items2dict  }}"
