- name: redirection using shell module
  hosts: Frontend
  tasks:
  - name: create ls -ltr
    ansible.builtin.shell: " ls -ltr > /tmp/output.txt" #shell module  in complex times we uise this when we need >,|,&& etc
    register: command_result 

  - name: print the result
    ansible.builtin.debug:
      msg: " {{ command_result }} "


- name: redirection using shell module
  hosts: Frontend
  tasks:
  - name: create ls -ltr
    ansible.builtin.command : ls -ltr  #command module easy to use mostly uses this
    register: command_result 

  - name: print the result
    ansible.builtin.debug:
      msg: " {{ command_result }} "
      

#       ---------------------------------OUTPUT-----------------------------
      
# TASK [print the result] ***************************************************************************************************************************************************************
# ok: [172.31.17.216] => {
#     "msg": " {'changed': True, 'stdout': '', 'stderr': '', 'rc': 0, 'cmd': 'ls -ltr > /tmp/output.txt', 'start': '2026-04-01 08:59:34.536087', 'end': '2026-04-01 08:59:34.543732', 'delta': '0:00:00.007645', 'msg': '', 'stdout_lines': [], 'stderr_lines': [], 'failed': False} "
# }

# PLAY [redirection using shell module] *************************************************************************************************************************************************

# TASK [Gathering Facts] ****************************************************************************************************************************************************************
# ok: [172.31.17.216]

# TASK [create ls -ltr] *****************************************************************************************************************************************************************
# changed: [172.31.17.216]

# TASK [print the result] ***************************************************************************************************************************************************************
# ok: [172.31.17.216] => {
#     "msg": " {'changed': True, 'stdout': 'total 0', 'stderr': '', 'rc': 0, 'cmd': ['ls', '-ltr'], 'start': '2026-04-01 08:59:40.643529', 'end': '2026-04-01 08:59:40.649308', 'delta': '0:00:00.005779', 'msg': '', 'stdout_lines': ['total 0'], 'stderr_lines': [], 'failed': False} "
# }

