[Frontend]
172.31.17.216 COURSE=VARIABLES NAME=VARDHAN DURATION="2 HOURS" ansible_user=ec2-user ansible_password=DevOps321


[local]
localhost

[local:vars]
COURSE=VARIABLES
NAME=VARDHAN
DURATION=1.5HR
GREETING="Hello from Inventory"